version: '3'
services:
  web:
    container_name: meduzzen-site
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${REACT_APP_API_PORT}:${REACT_APP_DOCKER_PORT}"
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: on-failure
